name: Denopendabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # modify to your convenient time

jobs:
  run:
    name: Run App
    runs-on: ubuntu-latest

    steps:
      # dispatch a `denopendabot_run` repository event
      - name: Dispatch Run
        uses: hasundue/denopendabot@0.16.1 # @denopendabot hasundue/denopendabot
        with: 
          mode: app
          base-branch: main 
          working-branch: denopendabot
          labels: dependencies
          auto-merge: any
